# Default values for eksdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
replicas: 3
version: '1.0'

# Service Specific Values
nodejs:
  image: 028429714899.dkr.ecr.ap-northeast-1.amazonaws.com/malakaj-demo
crystal:
  image: 028429714899.dkr.ecr.ap-northeast-1.amazonaws.com/ecsdemo-crystal
frontend:
  image: 028429714899.dkr.ecr.ap-northeast-1.amazonaws.com/ecsdemo-frontend
