apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingresslb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /server1
          pathType: Prefix
          backend:
            service:
              name: service1
              port:
                number: 80
        - path: /server2
          pathType: Prefix
          backend:
            service:
              name: service2
              port:
                number: 80
