apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2
  labels:
    app: service2
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: service2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service2
    spec:
      containers:
      - name: service1
        image: 028429714899.dkr.ecr.ap-northeast-1.amazonaws.com/server2:1.0
        ports:
        - containerPort: 80
